services:
  sort-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: sort-proxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CONTAINERS: 1
      POST: 1
      PING: 1
    networks:
      - sort
  sort-dev:
    image: bip/dev:latest
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    container_name: sort-dev
    restart: unless-stopped
    volumes:
      - ./data/dev:/app
      - ./data/ssh/authorized_keys:/home/bip/.ssh/authorized_keys:ro
    networks:
      - sort
  sort-prod:
    build:
      dockerfile: Dockerfile
      context: .
      target: prod
    image: bip/prod:latest
    container_name: sort-prod
    restart: unless-stopped
    volumes:
      - ./data/prod:/app
    networks:
      - sort
  sort-frpc:
    image: snowdreamtech/frpc:latest
    container_name: sort-frpc
    restart: always
    volumes:
      - ./data/frpc/frpc.toml:/etc/frp/frpc.toml:ro
    networks:
      - sort
networks:
  sort:
    driver: bridge
